"""remove unique conversation id

Revision ID: d6746d469e14
Revises: 80967e084526
Create Date: 2024-05-15 14:01:05.696034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6746d469e14'
down_revision: Union[str, None] = '80967e084526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_conversation_id_key', 'games', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('games_conversation_id_key', 'games', ['conversation_id'])
    # ### end Alembic commands ###
