"""add game_profiles

Revision ID: 72d8cfab0e3f
Revises: b1d1cf181dc9
Create Date: 2024-05-16 20:38:35.972531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d8cfab0e3f'
down_revision: Union[str, None] = 'b1d1cf181dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_to_registration', sa.Integer(), nullable=False),
    sa.Column('min_count_gamers', sa.Integer(), nullable=False),
    sa.Column('max_count_gamers', sa.Integer(), nullable=False),
    sa.Column('time_to_answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_to_registration', 'min_count_gamers', 'max_count_gamers', 'time_to_answer', name='profile_name')
    )
    op.add_column('games', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'games', 'game_settings', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'profile_id')
    op.drop_table('game_settings')
    # ### end Alembic commands ###
