"""more desription

Revision ID: be6971b4d0cf
Revises: d074b1eddca4
Create Date: 2024-05-18 18:13:19.955448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6971b4d0cf'
down_revision: Union[str, None] = 'd074b1eddca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_settings', 'description',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_settings', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
