"""add constraint key players

Revision ID: 80967e084526
Revises: 3bfe1c7f6512
Create Date: 2024-05-14 22:53:22.603177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80967e084526'
down_revision: Union[str, None] = '3bfe1c7f6512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vk_user_id_game_id', 'players', ['vk_user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vk_user_id_game_id', 'players', type_='unique')
    # ### end Alembic commands ###
