"""add game_profiles name/description

Revision ID: d074b1eddca4
Revises: 72d8cfab0e3f
Create Date: 2024-05-16 20:47:23.129705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd074b1eddca4'
down_revision: Union[str, None] = '72d8cfab0e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_settings', sa.Column('profile_name', sa.String(), nullable=False))
    op.add_column('game_settings', sa.Column('description', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'game_settings', ['profile_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_settings', type_='unique')
    op.drop_column('game_settings', 'description')
    op.drop_column('game_settings', 'profile_name')
    # ### end Alembic commands ###
