"""add player_answer_game uniq index

Revision ID: b1d1cf181dc9
Revises: d6746d469e14
Create Date: 2024-05-16 16:23:33.867004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d1cf181dc9'
down_revision: Union[str, None] = 'd6746d469e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_player_game_answer', 'player_answers_games', ['player_id', 'game_id', 'answer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_player_game_answer', 'player_answers_games', type_='unique')
    # ### end Alembic commands ###
